// src/components/tools/WoTStats.tsx
import { useState, useCallback } from 'react';
import wotConfig from '../../data/wot-config.json';

const APP_ID = wotConfig.applicationId;
const BASE_URL = 'https://api.worldoftanks.eu/wot';
const TIMEOUT_MS = 10_000;

interface VehicleStat {
  tank_id: number; name: string; battles: number; wins: number;
  damage_dealt: number; frags: number; spotted: number;
  winRate: number; avgDamage: number; wn8: number;
}

interface PlayerStats {
  account_id: number; nickname: string; battles: number; wins: number;
  damage_dealt: number; frags: number; winRate: number; avgDamage: number;
  avgFrags: number; avgSpotted: number; avgXp: number; survived: number;
  survivalRate: number; hitRate: number; wn8: number; vehicles: VehicleStat[];
}

// WN8 formula
function calcWn8(stats: { battles: number; wins: number; damage_dealt: number; frags: number; spotted: number; dropped_capture_points: number }, exp: { expDamage: number; expSpot: number; expFrag: number; expDef: number; expWinRate: number }) {
  if (stats.battles <= 0) return 0;
  const rD = (stats.damage_dealt / stats.battles) / exp.expDamage;
  const rS = (stats.spotted / stats.battles) / exp.expSpot;
  const rF = (stats.frags / stats.battles) / exp.expFrag;
  const rDf = (stats.dropped_capture_points / stats.battles) / exp.expDef;
  const rW = (stats.wins / stats.battles) / exp.expWinRate;
  const rWc = Math.max(0, (rW - 0.71) / 0.29);
  const rDc = Math.max(0, (rD - 0.22) / 0.78);
  const rFc = Math.max(0, Math.min(rDc + 0.2, (rF - 0.12) / 0.88));
  const rSc = Math.max(0, Math.min(rDc + 0.1, (rS - 0.38) / 0.62));
  const rDfc = Math.max(0, Math.min(rDc + 0.1, (rDf - 0.10) / 0.90));
  return Math.max(0, 980 * rDc + 210 * rDc * rFc + 155 * rFc * rSc + 75 * rDfc * rFc + 145 * Math.min(1.8, rWc));
}

async function fetchTimeout(url: string) {
  const c = new AbortController();
  const t = setTimeout(() => c.abort(), TIMEOUT_MS);
  try { const r = await fetch(url, { signal: c.signal }); clearTimeout(t); return r; }
  catch (e) { clearTimeout(t); throw e; }
}

function wn8Color(wn8: number) {
  if (wn8 >= 2450) return '#A020F0';
  if (wn8 >= 2000) return '#6040BF';
  if (wn8 >= 1600) return '#3972C6';
  if (wn8 >= 1200) return '#4099BF';
  if (wn8 >= 900) return '#4EAD4E';
  if (wn8 >= 650) return '#849B24';
  if (wn8 >= 450) return '#CC7A00';
  return '#CD3333';
}

function wn8Label(wn8: number) {
  if (wn8 >= 2450) return 'Super Unicum';
  if (wn8 >= 2000) return 'Unicum';
  if (wn8 >= 1600) return 'Great';
  if (wn8 >= 1200) return 'Very Good';
  if (wn8 >= 900) return 'Good';
  if (wn8 >= 650) return 'Above Average';
  if (wn8 >= 450) return 'Average';
  return 'Below Average';
}

export default function WoTStats() {
  const [username, setUsername] = useState(wotConfig.defaultPlayer);
  const [playerStats, setPlayerStats] = useState<PlayerStats | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [tab, setTab] = useState<'overview' | 'vehicles'>('overview');

  const search = useCallback(async (name?: string) => {
    const searchName = name ?? username;
    if (!searchName.trim()) return;
    setLoading(true); setError(null);
    try {
      // Step 1: search
      let res = await fetchTimeout(`${BASE_URL}/account/list/?application_id=${APP_ID}&search=${encodeURIComponent(searchName)}&limit=1`);
      const searchData = await res.json();
      if (!searchData.data?.length) throw new Error(`玩家 "${searchName}" 未找到`);
      const { account_id, nickname } = searchData.data[0];

      // Step 2: account info
      res = await fetchTimeout(`${BASE_URL}/account/info/?application_id=${APP_ID}&account_id=${account_id}`);
      const infoData = await res.json();
      const info = infoData.data?.[account_id];
      if (!info) throw new Error('账号数据不可用');
      const all = info.statistics?.all ?? {};
      const { battles = 0, wins = 0, damage_dealt = 0, frags = 0, spotted = 0, xp = 0, survived_battles = 0, hits = 0, shots = 0 } = all;

      // Step 3: vehicle stats
      res = await fetchTimeout(`${BASE_URL}/tanks/stats/?application_id=${APP_ID}&account_id=${account_id}&fields=tank_id,all`);
      const tanksData = await res.json();
      const tankList: any[] = tanksData.data?.[account_id] ?? [];
      const activeTanks = tankList.filter(t => t.all?.battles > 0);

      // Fetch vehicle names
      const nameMap = new Map<number, string>();
      const tankIds = activeTanks.map(t => t.tank_id);
      for (let i = 0; i < tankIds.length; i += 100) {
        try {
          const ids = tankIds.slice(i, i + 100).join(',');
          const r = await fetchTimeout(`${BASE_URL}/encyclopedia/vehicles/?application_id=${APP_ID}&tank_id=${ids}&fields=tank_id,short_name,name`);
          const j = await r.json();
          if (j.data) Object.entries(j.data).forEach(([id, v]: any) => { if (v?.short_name || v?.name) nameMap.set(Number(id), v.short_name || v.name); });
        } catch {}
      }

      // Fetch WN8 expected values
      let expMap = new Map<number, any>();
      try {
        const r = await fetchTimeout('https://static.modxvm.com/wn8-data-exp/json/wn8exp.json');
        const d = await r.json();
        d.data?.forEach((e: any) => expMap.set(e.IDNum, e));
      } catch {}

      // Build vehicle stats
      const vehicles: VehicleStat[] = activeTanks.map(t => {
        const s = t.all;
        const exp = expMap.get(t.tank_id);
        const wn8 = exp ? calcWn8({ battles: s.battles, wins: s.wins, damage_dealt: s.damage_dealt, frags: s.frags, spotted: s.spotted, dropped_capture_points: s.dropped_capture_points }, exp) : 0;
        return {
          tank_id: t.tank_id, name: nameMap.get(t.tank_id) ?? `#${t.tank_id}`,
          battles: s.battles, wins: s.wins, damage_dealt: s.damage_dealt, frags: s.frags, spotted: s.spotted,
          winRate: s.battles > 0 ? s.wins / s.battles : 0, avgDamage: s.battles > 0 ? Math.round(s.damage_dealt / s.battles) : 0, wn8,
        };
      }).sort((a, b) => b.battles - a.battles).slice(0, 20);

      // Overall WN8
      let overallWn8 = 0;
      if (vehicles.length > 0) {
        let tw = 0, tb = 0;
        vehicles.forEach(v => { if (v.wn8 > 0) { tw += v.wn8 * v.battles; tb += v.battles; } });
        overallWn8 = tb > 0 ? tw / tb : 0;
      }

      setPlayerStats({
        account_id, nickname, battles, wins, damage_dealt, frags,
        winRate: battles > 0 ? wins / battles : 0,
        avgDamage: battles > 0 ? Math.round(damage_dealt / battles) : 0,
        avgFrags: battles > 0 ? frags / battles : 0,
        avgSpotted: battles > 0 ? spotted / battles : 0,
        avgXp: battles > 0 ? Math.round(xp / battles) : 0,
        survived: survived_battles,
        survivalRate: battles > 0 ? survived_battles / battles : 0,
        hitRate: shots > 0 ? hits / shots : 0,
        wn8: overallWn8, vehicles,
      });
    } catch (e: any) {
      setError(e?.message ?? '查询失败');
    } finally {
      setLoading(false);
    }
  }, [username]);

  const pct = (v: number) => (v * 100).toFixed(1) + '%';

  return (
    <div className="min-h-[80vh] font-sans" style={{ background: '#1a1a2e' }}>
      <div className="max-w-3xl mx-auto px-4 py-8">
        <div className="flex justify-center mb-4">
          <img src="/img/tools/wot.png" alt="坦克世界" className="w-16 h-16" />
        </div>
        <h1 className="text-center text-2xl font-bold text-amber-400 mb-2">坦克世界 · 欧服战绩</h1>
        <p className="text-center text-xs text-amber-400/50 mb-8">World of Tanks EU Server</p>

        {/* Search */}
        <div className="flex gap-2 mb-8">
          <input
            type="text" value={username}
            onChange={e => setUsername(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && search()}
            placeholder="输入玩家昵称..."
            className="flex-1 px-4 py-2.5 bg-white/5 border border-amber-400/30 rounded-lg text-white placeholder-white/30 focus:outline-none focus:border-amber-400"
          />
          <button onClick={() => search()} disabled={loading} className="px-6 py-2.5 bg-amber-500 hover:bg-amber-400 text-black font-semibold rounded-lg transition-colors disabled:opacity-50">
            {loading ? '查询中...' : '查询'}
          </button>
        </div>

        {error && <div className="text-center text-red-400 text-sm mb-4 p-3 bg-red-400/10 rounded-lg">{error}</div>}

        {playerStats && (
          <>
            {/* Header */}
            <div className="text-center mb-6">
              <h2 className="text-xl font-bold text-white">{playerStats.nickname}</h2>
              <div className="flex items-center justify-center gap-3 mt-2">
                <div className="text-3xl font-bold" style={{ color: wn8Color(playerStats.wn8) }}>
                  {Math.round(playerStats.wn8)}
                </div>
                <div className="text-left">
                  <div className="text-xs text-white/50">WN8</div>
                  <div className="text-sm font-semibold" style={{ color: wn8Color(playerStats.wn8) }}>{wn8Label(playerStats.wn8)}</div>
                </div>
              </div>
            </div>

            {/* Tabs */}
            <div className="flex gap-2 mb-6 justify-center">
              <button onClick={() => setTab('overview')} className={`px-4 py-2 rounded-lg text-sm transition-colors ${tab === 'overview' ? 'bg-amber-500 text-black' : 'bg-white/5 text-white/60 hover:text-white'}`}>总览</button>
              <button onClick={() => setTab('vehicles')} className={`px-4 py-2 rounded-lg text-sm transition-colors ${tab === 'vehicles' ? 'bg-amber-500 text-black' : 'bg-white/5 text-white/60 hover:text-white'}`}>车辆 Top 20</button>
            </div>

            {tab === 'overview' && (
              <div>
                <div className="text-center text-xs text-amber-400/50 mb-2">基于全部数据</div>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                {[
                  { label: '总场次', value: playerStats.battles.toLocaleString() },
                  { label: '胜率', value: pct(playerStats.winRate) },
                  { label: '场均伤害', value: playerStats.avgDamage.toLocaleString() },
                  { label: '场均击杀', value: playerStats.avgFrags.toFixed(2) },
                  { label: '场均侦察', value: playerStats.avgSpotted.toFixed(2) },
                  { label: '场均经验', value: playerStats.avgXp.toLocaleString() },
                  { label: '存活率', value: pct(playerStats.survivalRate) },
                  { label: '命中率', value: pct(playerStats.hitRate) },
                ].map(s => (
                  <div key={s.label} className="bg-white/5 border border-white/10 rounded-lg p-4 text-center">
                    <div className="text-xs text-white/40 uppercase tracking-wider mb-1">{s.label}</div>
                    <div className="text-lg font-bold text-white">{s.value}</div>
                  </div>
                ))}
              </div>
              </div>
            )}

            {tab === 'vehicles' && (
              <div className="overflow-x-auto">
                <div className="text-center text-xs text-amber-400/50 mb-2">基于全部数据</div>
                <table className="w-full text-sm">
                  <thead>
                    <tr className="text-left text-white/40 text-xs uppercase border-b border-white/10">
                      <th className="py-2 px-2">车辆</th>
                      <th className="py-2 px-2 text-right">场次</th>
                      <th className="py-2 px-2 text-right">胜率</th>
                      <th className="py-2 px-2 text-right">场均伤害</th>
                      <th className="py-2 px-2 text-right">WN8</th>
                    </tr>
                  </thead>
                  <tbody>
                    {playerStats.vehicles.map(v => (
                      <tr key={v.tank_id} className="border-b border-white/5 hover:bg-white/5">
                        <td className="py-2 px-2 text-white">{v.name}</td>
                        <td className="py-2 px-2 text-right text-white/60">{v.battles}</td>
                        <td className="py-2 px-2 text-right text-white/60">{pct(v.winRate)}</td>
                        <td className="py-2 px-2 text-right text-white/60">{v.avgDamage}</td>
                        <td className="py-2 px-2 text-right font-bold" style={{ color: wn8Color(v.wn8) }}>{Math.round(v.wn8)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </>
        )}

        {!playerStats && !loading && !error && (
          <div className="text-center text-white/30 py-16">
            <div className="text-5xl mb-4">🎯</div>
            <p>输入玩家昵称开始查询</p>
            <p className="text-xs mt-1">默认查询：{wotConfig.defaultPlayer}</p>
          </div>
        )}
      </div>
    </div>
  );
}

// src/tools/wot/WoTStats.vue
<script setup lang="ts">
import { ref, onMounted, computed } from "vue"
import { RouterLink } from "vue-router"
import { searchPlayer, type WoTPlayerStats, type VehicleStat } from "../../composables/useWargamingApi"
import wotConfig from "../../data/wot-config.json"
import ErrorBoundary from "../../components/ui/ErrorBoundary.vue"

const username = ref(wotConfig.defaultPlayer)
const loading = ref(false)
const playerData = ref<WoTPlayerStats | null>(null)
const errorMsg = ref<string | null>(null)
const notFound = ref(false)
const activeTab = ref<"vehicles" | "battles">("vehicles")

function wn8Color(wn8: number): string {
  if (wn8 < 300) return "#CD3333"
  if (wn8 < 900) return "#CD7700"
  if (wn8 < 1650) return "#CCB800"
  if (wn8 < 2450) return "#4D7326"
  if (wn8 < 3000) return "#4099BF"
  return "#B24CCC"
}

function wn8Label(wn8: number): string {
  if (wn8 < 300) return "很差"
  if (wn8 < 900) return "较差"
  if (wn8 < 1650) return "平均"
  if (wn8 < 2450) return "良好"
  if (wn8 < 3000) return "优秀"
  return "超神"
}

function pct(v: number): string {
  return (v * 100).toFixed(1) + "%"
}

async function doSearch() {
  if (!username.value.trim()) return
  loading.value = true
  errorMsg.value = null
  notFound.value = false
  playerData.value = null
  try {
    playerData.value = await searchPlayer(username.value.trim())
  } catch (e: unknown) {
    if (e && typeof e === "object" && "notFound" in e) {
      notFound.value = true
    } else {
      errorMsg.value = e instanceof Error ? e.message : "请求失败"
    }
  } finally {
    loading.value = false
  }
}

onMounted(() => { doSearch() })
</script>

<template>
  <ErrorBoundary>
  <div class="wot-page min-h-screen">

    <!-- WoT hero banner -->
    <div class="wot-banner relative overflow-hidden">
      <div class="wot-banner-overlay" />
      <div class="relative z-10 p-4 flex items-center justify-between">
        <RouterLink to="/" class="inline-flex items-center gap-2 px-3 py-1 border border-[#555] text-[#AAA] hover:bg-[#2A2A2A] transition-colors text-sm font-mono rounded">
          ← 返回主页
        </RouterLink>
        <h1 class="font-mono text-lg tracking-widest" style="color:#C0C0C0;">🛡 坦克世界 · 欧服</h1>
        <div class="w-24" />
      </div>
      <!-- Tank silhouette SVG -->
      <div class="flex justify-center pb-6 relative z-10">
        <svg viewBox="0 0 320 100" fill="none" xmlns="http://www.w3.org/2000/svg" width="320" height="100" opacity="0.6">
          <rect x="30" y="55" width="260" height="35" rx="6" fill="#2A2A2A" stroke="#444" stroke-width="1"/>
          <rect x="70" y="28" width="160" height="38" rx="5" fill="#333" stroke="#444" stroke-width="1"/>
          <rect x="110" y="12" width="90" height="22" rx="4" fill="#2A2A2A" stroke="#444" stroke-width="1"/>
          <rect x="190" y="15" width="80" height="8" rx="4" fill="#3A3A3A" stroke="#555" stroke-width="1"/>
          <circle cx="60" cy="90" r="12" fill="#222" stroke="#555" stroke-width="2"/>
          <circle cx="60" cy="90" r="6" fill="#333"/>
          <circle cx="110" cy="90" r="12" fill="#222" stroke="#555" stroke-width="2"/>
          <circle cx="110" cy="90" r="6" fill="#333"/>
          <circle cx="160" cy="90" r="12" fill="#222" stroke="#555" stroke-width="2"/>
          <circle cx="160" cy="90" r="6" fill="#333"/>
          <circle cx="210" cy="90" r="12" fill="#222" stroke="#555" stroke-width="2"/>
          <circle cx="210" cy="90" r="6" fill="#333"/>
          <circle cx="260" cy="90" r="12" fill="#222" stroke="#555" stroke-width="2"/>
          <circle cx="260" cy="90" r="6" fill="#333"/>
        </svg>
      </div>
    </div>

    <div class="max-w-4xl mx-auto px-4 pb-12">

      <!-- Search -->
      <div class="flex gap-2 my-6">
        <input v-model="username" type="text" placeholder="输入欧服玩家名..." class="search-input flex-1 px-4 py-2 font-mono text-sm rounded" @keyup.enter="doSearch"/>
        <button @click="doSearch" class="search-btn px-5 py-2 font-mono text-sm rounded">搜索</button>
      </div>

      <!-- Loading -->
      <div v-if="loading" class="flex flex-col items-center gap-4 py-16">
        <div class="tracks-spinner">
          <div class="track-block" v-for="i in 5" :key="i" :style="{ animationDelay: `${(i-1)*0.15}s` }"></div>
        </div>
        <p class="font-mono text-sm" style="color:#666;">正在搜索玩家数据...</p>
      </div>

      <!-- Not found -->
      <div v-else-if="notFound" class="text-center py-12">
        <p class="font-mono text-lg mb-2" style="color:#CD3333;">⚠ 玩家未找到</p>
        <p class="font-mono text-sm" style="color:#666;">请检查玩家名是否正确（欧服）</p>
      </div>

      <!-- Error -->
      <div v-else-if="errorMsg" class="text-center py-12">
        <p class="font-mono mb-4" style="color:#CD3333;">⚠ {{ errorMsg }}</p>
        <button @click="doSearch" class="search-btn px-5 py-2 font-mono text-sm rounded">重试</button>
      </div>

      <!-- Player data -->
      <div v-else-if="playerData">

        <!-- Player header card -->
        <div class="steel-card p-5 mb-4 flex items-center justify-between flex-wrap gap-4">
          <div>
            <h2 class="font-mono text-2xl font-bold" style="color:#E0E0E0;">{{ playerData.nickname }}</h2>
            <p class="font-mono text-xs mt-1" style="color:#555;">Account ID: {{ playerData.account_id }}</p>
          </div>
          <div class="text-right">
            <div class="font-mono text-3xl font-bold" :style="{ color: wn8Color(playerData.wn8) }">
              {{ Math.round(playerData.wn8) }}
            </div>
            <div class="font-mono text-sm font-semibold" :style="{ color: wn8Color(playerData.wn8) }">
              WN8 · {{ wn8Label(playerData.wn8) }}
            </div>
          </div>
        </div>

        <!-- Tabs -->
        <div class="flex gap-1 mb-4">
          <button @click="activeTab = 'vehicles'" class="tab-btn" :class="{ active: activeTab === 'vehicles' }">🚗 车辆战绩</button>
          <button @click="activeTab = 'battles'" class="tab-btn" :class="{ active: activeTab === 'battles' }">📊 场次详情</button>
        </div>

        <!-- Tab: Vehicles -->
        <div v-if="activeTab === 'vehicles'">
          <div v-if="playerData.vehicles.length > 0" class="steel-card overflow-hidden">
            <div class="px-4 py-3 border-b border-[#333] flex items-center justify-between">
              <span class="font-mono text-sm" style="color:#C0C0C0;">Top {{ playerData.vehicles.length }} 车辆（按场次排序）</span>
            </div>
            <div class="overflow-x-auto">
              <table class="w-full font-mono text-sm">
                <thead>
                  <tr style="background:#1A1A1A;">
                    <th class="px-4 py-2 text-left" style="color:#888;">车辆</th>
                    <th class="px-4 py-2 text-right" style="color:#888;">场次</th>
                    <th class="px-4 py-2 text-right" style="color:#888;">胜率</th>
                    <th class="px-4 py-2 text-right" style="color:#888;">场均伤害</th>
                    <th class="px-4 py-2 text-right" style="color:#888;">WN8</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="v in playerData.vehicles" :key="v.tank_id" class="border-t border-[#2A2A2A] hover:bg-[#1E1E1E] transition-colors">
                    <td class="px-4 py-2.5" style="color:#E0E0E0;">{{ v.name }}</td>
                    <td class="px-4 py-2.5 text-right" style="color:#A0A0A0;">{{ v.battles.toLocaleString() }}</td>
                    <td class="px-4 py-2.5 text-right" style="color:#A0A0A0;">{{ pct(v.winRate) }}</td>
                    <td class="px-4 py-2.5 text-right" style="color:#A0A0A0;">{{ v.avgDamage.toLocaleString() }}</td>
                    <td class="px-4 py-2.5 text-right font-bold" :style="{ color: wn8Color(v.wn8) }">{{ Math.round(v.wn8) }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div v-else class="text-center py-8 font-mono text-sm" style="color:#555;">暂无车辆数据</div>
        </div>

        <!-- Tab: Battle Details -->
        <div v-if="activeTab === 'battles'">
          <!-- Overview stats grid -->
          <div class="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-4">
            <div class="stat-box">
              <div class="stat-label">总场次</div>
              <div class="stat-val">{{ playerData.battles.toLocaleString() }}</div>
            </div>
            <div class="stat-box">
              <div class="stat-label">胜率</div>
              <div class="stat-val">{{ pct(playerData.winRate) }}</div>
            </div>
            <div class="stat-box">
              <div class="stat-label">场均伤害</div>
              <div class="stat-val">{{ playerData.avgDamage.toLocaleString() }}</div>
            </div>
            <div class="stat-box">
              <div class="stat-label">场均击杀</div>
              <div class="stat-val">{{ playerData.avgFrags.toFixed(2) }}</div>
            </div>
          </div>

          <div class="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-4">
            <div class="stat-box">
              <div class="stat-label">场均侦查</div>
              <div class="stat-val">{{ playerData.avgSpotted.toFixed(2) }}</div>
            </div>
            <div class="stat-box">
              <div class="stat-label">场均经验</div>
              <div class="stat-val">{{ playerData.avgXp.toLocaleString() }}</div>
            </div>
            <div class="stat-box">
              <div class="stat-label">存活率</div>
              <div class="stat-val">{{ pct(playerData.survivalRate) }}</div>
            </div>
            <div class="stat-box">
              <div class="stat-label">命中率</div>
              <div class="stat-val">{{ pct(playerData.hitRate) }}</div>
            </div>
          </div>

          <!-- Derived stats -->
          <div class="grid grid-cols-2 sm:grid-cols-3 gap-3 mb-4">
            <div class="stat-box">
              <div class="stat-label">总胜场</div>
              <div class="stat-val">{{ playerData.wins.toLocaleString() }}</div>
            </div>
            <div class="stat-box">
              <div class="stat-label">总伤害</div>
              <div class="stat-val">{{ playerData.damage_dealt.toLocaleString() }}</div>
            </div>
            <div class="stat-box">
              <div class="stat-label">总击杀</div>
              <div class="stat-val">{{ playerData.frags.toLocaleString() }}</div>
            </div>
          </div>

          <!-- WN8 color legend -->
          <div class="steel-card p-4">
            <div class="font-mono text-xs mb-3" style="color:#888;">WN8 评级说明</div>
            <div class="flex flex-wrap gap-2">
              <span v-for="[label, color] in [['很差 &lt;300','#CD3333'],['较差 &lt;900','#CD7700'],['平均 &lt;1650','#CCB800'],['良好 &lt;2450','#4D7326'],['优秀 &lt;3000','#4099BF'],['超神 3000+','#B24CCC']]" :key="label" class="font-mono text-xs px-2 py-1 rounded" :style="`color:${color}; border: 1px solid ${color}40; background: ${color}15`">{{ label }}</span>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
  </ErrorBoundary>
</template>

<style scoped>
.wot-page { background: #141414; font-family: "Inter", system-ui, sans-serif; }

.wot-banner {
  background: linear-gradient(180deg, #0A0A0A 0%, #1A1A1A 100%);
  border-bottom: 1px solid #2A2A2A;
}
.wot-banner-overlay {
  position: absolute; inset: 0;
  background: radial-gradient(ellipse at center, rgba(192,192,192,0.03) 0%, transparent 70%);
}

.search-input { background: #111; border: 1px solid #333; color: #E0E0E0; outline: none; }
.search-input:focus { border-color: #666; }
.search-input::placeholder { color: #444; }
.search-btn { background: #2A2A2A; border: 1px solid #444; color: #C0C0C0; cursor: pointer; transition: background 0.15s; }
.search-btn:hover { background: #333; }

.tracks-spinner { display: flex; gap: 6px; align-items: flex-end; }
.track-block { width: 12px; height: 12px; background: #444; border-radius: 2px; animation: track-bounce 0.8s ease-in-out infinite alternate; }
@keyframes track-bounce { from { transform: translateY(0); background: #444; } to { transform: translateY(-12px); background: #888; } }

.steel-card { background: #1E1E1E; border: 1px solid #2E2E2E; border-radius: 8px; }

.stat-box { background: #1E1E1E; border: 1px solid #2E2E2E; padding: 16px 12px; text-align: center; border-radius: 8px; }
.stat-label { font-size: 11px; color: #555; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 6px; font-family: "Courier New", monospace; }
.stat-val { font-size: 1.4rem; font-weight: bold; color: #C0C0C0; font-family: "Courier New", monospace; }

.tab-btn { padding: 8px 20px; font-size: 13px; border: 1px solid #333; background: #1A1A1A; color: #888; cursor: pointer; border-radius: 6px; transition: all 0.15s; font-family: "Courier New", monospace; }
.tab-btn:hover { background: #222; color: #C0C0C0; }
.tab-btn.active { background: #2A2A2A; border-color: #555; color: #E0E0E0; }
</style>
