// src/components/tools/MusicPlayer.tsx
import { useState, useEffect, useRef, useCallback } from 'react';
import musicData from '../../data/music.json';

interface Track {
  id: string;
  title: string;
  album: string;
  coverUrl: string;
  src: string;
}

type RepeatMode = 'none' | 'single' | 'playlist';

function fisherYates(n: number): number[] {
  const arr = Array.from({ length: n }, (_, i) => i);
  for (let i = n - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

const tracks: Track[] = musicData.tracks as Track[];

export default function MusicPlayer() {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [volume, setVolume] = useState(0.8);
  const [shuffleMode, setShuffleMode] = useState(false);
  const [repeatMode, setRepeatMode] = useState<RepeatMode>('none');
  const [shuffleOrder, setShuffleOrder] = useState<number[]>([]);
  const [shufflePos, setShufflePos] = useState(0);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [showPlaylist, setShowPlaylist] = useState(false);
  const [_consecutiveErrors, setConsecutiveErrors] = useState(0);
  const audioRef = useRef<HTMLAudioElement>(null);
  const generationRef = useRef(0);

  const currentTrack = tracks[currentIndex] ?? null;

  const generateShuffle = useCallback((idx: number) => {
    const order = fisherYates(tracks.length);
    setShuffleOrder(order);
    const pos = order.indexOf(idx);
    setShufflePos(pos >= 0 ? pos : 0);
    return order;
  }, []);

  const goNext = useCallback(() => {
    if (tracks.length === 0) return;
    if (repeatMode === 'single') return;
    const n = tracks.length;
    if (shuffleMode) {
      let order = shuffleOrder;
      if (order.length !== n) order = generateShuffle(currentIndex);
      const newPos = (shufflePos + 1) % n;
      setShufflePos(newPos);
      setCurrentIndex(order[newPos]);
    } else {
      setCurrentIndex(prev => (prev + 1) % n);
    }
  }, [repeatMode, shuffleMode, shuffleOrder, shufflePos, currentIndex, generateShuffle]);

  const goPrev = useCallback(() => {
    if (tracks.length === 0) return;
    if (repeatMode === 'single') return;
    const n = tracks.length;
    if (shuffleMode) {
      let order = shuffleOrder;
      if (order.length !== n) order = generateShuffle(currentIndex);
      const newPos = (shufflePos - 1 + n) % n;
      setShufflePos(newPos);
      setCurrentIndex(order[newPos]);
    } else {
      setCurrentIndex(prev => (prev - 1 + n) % n);
    }
  }, [repeatMode, shuffleMode, shuffleOrder, shufflePos, currentIndex, generateShuffle]);

  // Play/pause effect
  useEffect(() => {
    const audio = audioRef.current;
    if (!audio || !currentTrack) return;
    generationRef.current++;
    const gen = generationRef.current;
    audio.src = currentTrack.src;
    audio.load();
    if (isPlaying) {
      audio.play().catch(() => {
        if (gen === generationRef.current) setIsPlaying(false);
      });
    }
  }, [currentIndex]);

  useEffect(() => {
    const audio = audioRef.current;
    if (!audio) return;
    if (isPlaying) {
      audio.play().catch(() => {});
    } else {
      audio.pause();
    }
  }, [isPlaying]);

  useEffect(() => {
    const audio = audioRef.current;
    if (audio) audio.volume = volume;
  }, [volume]);

  // Time update
  useEffect(() => {
    const audio = audioRef.current;
    if (!audio) return;
    const onTimeUpdate = () => setCurrentTime(audio.currentTime);
    const onLoadedMetadata = () => setDuration(audio.duration);
    const onEnded = () => {
      if (repeatMode === 'single') {
        audio.currentTime = 0;
        audio.play().catch(() => {});
      } else {
        goNext();
      }
    };
    const onError = () => {
      setConsecutiveErrors(prev => {
        if (prev + 1 >= 3) {
          setIsPlaying(false);
          return 0;
        }
        goNext();
        return prev + 1;
      });
    };
    const onPlay = () => { setConsecutiveErrors(0); };
    audio.addEventListener('timeupdate', onTimeUpdate);
    audio.addEventListener('loadedmetadata', onLoadedMetadata);
    audio.addEventListener('ended', onEnded);
    audio.addEventListener('error', onError);
    audio.addEventListener('playing', onPlay);
    return () => {
      audio.removeEventListener('timeupdate', onTimeUpdate);
      audio.removeEventListener('loadedmetadata', onLoadedMetadata);
      audio.removeEventListener('ended', onEnded);
      audio.removeEventListener('error', onError);
      audio.removeEventListener('playing', onPlay);
    };
  }, [repeatMode, goNext]);

  const seek = (e: React.MouseEvent<HTMLDivElement>) => {
    const audio = audioRef.current;
    if (!audio || !duration) return;
    const rect = e.currentTarget.getBoundingClientRect();
    const x = (e.clientX - rect.left) / rect.width;
    audio.currentTime = x * duration;
  };

  const jumpTo = (idx: number) => {
    setCurrentIndex(idx);
    setIsPlaying(true);
    if (shuffleMode) {
      const pos = shuffleOrder.indexOf(idx);
      setShufflePos(pos >= 0 ? pos : 0);
    }
  };

  const fmtTime = (s: number) => {
    if (!s || isNaN(s)) return '0:00';
    const m = Math.floor(s / 60);
    const sec = Math.floor(s % 60);
    return `${m}:${sec.toString().padStart(2, '0')}`;
  };

  const cycleRepeat = () => {
    const modes: RepeatMode[] = ['none', 'playlist', 'single'];
    const idx = modes.indexOf(repeatMode);
    setRepeatMode(modes[(idx + 1) % modes.length]);
  };

  const repeatIcon = repeatMode === 'single' ? '🔂' : repeatMode === 'playlist' ? '🔁' : '➡️';

  return (
    <div className="min-h-[80vh] relative" style={{ background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)' }}>
      <audio ref={audioRef} preload="metadata" />

      <div className="max-w-lg mx-auto px-4 py-8">
        {/* Cover Art */}
        <div className="flex justify-center mb-6">
          <div className={`w-48 h-48 rounded-full border-4 border-white/10 shadow-2xl overflow-hidden ${isPlaying ? 'animate-spin-slow' : ''}`}>
            {currentTrack?.coverUrl ? (
              <img src={currentTrack.coverUrl} alt={currentTrack.title} className="w-full h-full object-cover" />
            ) : (
              <div className="w-full h-full bg-gradient-to-br from-purple-600 to-pink-500 flex items-center justify-center text-5xl">🎵</div>
            )}
          </div>
        </div>

        {/* Track info */}
        <div className="text-center mb-4">
          <h2 className="text-xl font-bold text-white truncate">{currentTrack?.title ?? '未知曲目'}</h2>
          <p className="text-sm text-white/50 mt-1">{currentTrack?.album ?? ''}</p>
        </div>

        {/* Progress bar */}
        <div className="mb-4">
          <div className="h-1.5 bg-white/10 rounded-full cursor-pointer relative" onClick={seek}>
            <div className="h-full bg-gradient-to-r from-purple-500 to-pink-500 rounded-full transition-all" style={{ width: duration ? `${(currentTime / duration) * 100}%` : '0%' }} />
          </div>
          <div className="flex justify-between text-xs text-white/40 mt-1">
            <span>{fmtTime(currentTime)}</span>
            <span>{fmtTime(duration)}</span>
          </div>
        </div>

        {/* Controls */}
        <div className="flex items-center justify-center gap-6 mb-6">
          <button onClick={() => { setShuffleMode(!shuffleMode); if (!shuffleMode) generateShuffle(currentIndex); }} className={`text-lg transition-opacity ${shuffleMode ? 'opacity-100' : 'opacity-40'} hover:opacity-100`} title="随机播放">🔀</button>
          <button onClick={goPrev} className="text-2xl text-white/80 hover:text-white transition-colors">⏮</button>
          <button onClick={() => setIsPlaying(!isPlaying)} className="w-14 h-14 rounded-full bg-gradient-to-r from-purple-500 to-pink-500 flex items-center justify-center text-2xl text-white shadow-lg hover:scale-105 transition-transform">
            {isPlaying ? '⏸' : '▶'}
          </button>
          <button onClick={goNext} className="text-2xl text-white/80 hover:text-white transition-colors">⏭</button>
          <button onClick={cycleRepeat} className={`text-lg transition-opacity ${repeatMode !== 'none' ? 'opacity-100' : 'opacity-40'} hover:opacity-100`} title={`循环模式: ${repeatMode}`}>{repeatIcon}</button>
        </div>

        {/* Volume */}
        <div className="flex items-center gap-3 mb-6 px-4">
          <span className="text-white/50 text-sm">🔊</span>
          <input type="range" min="0" max="1" step="0.01" value={volume} onChange={e => setVolume(Number(e.target.value))} className="flex-1 accent-purple-500 h-1" />
          <span className="text-white/40 text-xs w-8 text-right">{Math.round(volume * 100)}</span>
        </div>

        {/* Playlist toggle */}
        <button onClick={() => setShowPlaylist(!showPlaylist)} className="w-full text-center text-sm text-white/50 hover:text-white/80 transition-colors py-2">
          {showPlaylist ? '▲ 收起列表' : '▼ 播放列表'} ({tracks.length} 首)
        </button>

        {/* Playlist */}
        {showPlaylist && (
          <div className="mt-2 max-h-80 overflow-y-auto rounded-xl bg-black/30 backdrop-blur-sm border border-white/5">
            {tracks.map((track, idx) => (
              <button
                key={track.id}
                onClick={() => jumpTo(idx)}
                className={`w-full text-left px-4 py-3 flex items-center gap-3 hover:bg-white/5 transition-colors border-b border-white/5 last:border-b-0 ${idx === currentIndex ? 'bg-white/10' : ''}`}
              >
                <span className="text-xs text-white/30 w-6 text-right">{idx + 1}</span>
                <div className="flex-1 min-w-0">
                  <div className={`text-sm truncate ${idx === currentIndex ? 'text-purple-400' : 'text-white/80'}`}>{track.title}</div>
                  <div className="text-xs text-white/30 truncate">{track.album}</div>
                </div>
                {idx === currentIndex && isPlaying && <span className="text-purple-400 text-xs">♪</span>}
              </button>
            ))}
          </div>
        )}
      </div>

      <style>{`
        @keyframes spin-slow { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
        .animate-spin-slow { animation: spin-slow 8s linear infinite; }
      `}</style>
    </div>
  );
}

// src/tools/music/MusicPlayer.vue
﻿<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted, computed } from 'vue'
import { RouterLink } from 'vue-router'
import { useAudioStore } from '../../stores/audio'
import ErrorBoundary from '../../components/ui/ErrorBoundary.vue'

const store = useAudioStore()
const audioRef = ref<HTMLAudioElement | null>(null)
const currentTime = ref(0)
const duration = ref(0)
const isReady = ref(false)

const repeatIcon = computed(() => {
  if (store.repeatMode === 'single') return '🔂'
  if (store.repeatMode === 'playlist') return '🔁'
  return '➡'
})

const repeatLabel = computed(() => {
  if (store.repeatMode === 'single') return '单曲'
  if (store.repeatMode === 'playlist') return '列表'
  return '顺序'
})

const progressPct = computed(() =>
  duration.value > 0 ? (currentTime.value / duration.value) * 100 : 0
)

function formatTime(s: number): string {
  if (!isFinite(s) || isNaN(s)) return '0:00'
  const m = Math.floor(s / 60)
  const sec = Math.floor(s % 60)
  return `${m}:${sec.toString().padStart(2, '0')}`
}

function cycleRepeat() {
  const modes = ['none', 'single', 'playlist'] as const
  const idx = modes.indexOf(store.repeatMode)
  store.setRepeat(modes[(idx + 1) % modes.length])
}

function togglePlay() {
  const audio = audioRef.value
  if (!audio) return
  if (store.isPlaying) {
    audio.pause()
    store.pause()
  } else {
    audio.play().then(() => store.play()).catch(() => {})
  }
}

function seekTo(e: MouseEvent) {
  const bar = e.currentTarget as HTMLElement
  const rect = bar.getBoundingClientRect()
  const pct = (e.clientX - rect.left) / rect.width
  const audio = audioRef.value
  if (audio && isFinite(audio.duration)) {
    audio.currentTime = pct * audio.duration
  }
}

function handleEnded() {
  if (store.repeatMode === 'single') {
    audioRef.value?.play().catch(() => {})
  } else {
    store.next()
  }
}

function handleError() {
  isReady.value = false
  store.onAudioError()
}

function handleTimeUpdate() {
  currentTime.value = audioRef.value?.currentTime ?? 0
}

function handleLoadedMetadata() {
  duration.value = audioRef.value?.duration ?? 0
  isReady.value = true
}

function handleCanPlay() {
  isReady.value = true
}

// When track changes, load new src
watch(() => store.currentIndex, () => {
  const audio = audioRef.value
  if (!audio) return
  isReady.value = false
  currentTime.value = 0
  duration.value = 0
  const track = store.currentTrack
  if (track) {
    audio.src = track.src
    audio.load()
    if (store.isPlaying) {
      audio.play().catch(() => {})
    }
  }
})

watch(() => store.volume, (v) => {
  if (audioRef.value) audioRef.value.volume = v
})

onMounted(() => {
  const audio = audioRef.value
  if (!audio) return
  audio.volume = store.volume
  const track = store.currentTrack
  if (track) {
    audio.src = track.src
    audio.load()
  }
})

onUnmounted(() => {
  store.pause()
})

// Background blur color from cover
const bgStyle = computed(() => {
  const cover = store.currentTrack?.coverUrl
  if (cover && !cover.includes('placeholder')) {
    return `background: linear-gradient(135deg, #1A0A00 0%, #2A1200 50%, #1A0A00 100%);`
  }
  return 'background: linear-gradient(135deg, #1A0A00 0%, #2A1200 50%, #1A0A00 100%);'
})
</script>

<template>
  <ErrorBoundary>
  <div class="music-page min-h-screen relative overflow-hidden" :style="bgStyle">

    <!-- Blurred album art background -->
    <div
      v-if="store.currentTrack?.coverUrl"
      class="absolute inset-0 pointer-events-none"
      :style="`background-image: url('${store.currentTrack.coverUrl}'); background-size: cover; background-position: center; filter: blur(60px) brightness(0.25); transform: scale(1.1);`"
    />
    <div class="absolute inset-0 bg-black/50 pointer-events-none" />

    <!-- Back button -->
    <div class="p-4 relative z-10">
      <RouterLink to="/" class="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg border border-amber-700/50 text-amber-400/80 hover:bg-amber-900/30 transition-colors text-sm backdrop-blur-sm">
        ← 返回主页
      </RouterLink>
    </div>

    <div class="relative z-10 max-w-5xl mx-auto px-4 pb-12">
      <h1 class="text-center mb-8 text-xl font-semibold tracking-widest" style="color:#D4A96A;">
        🎵 陈奕迅 · 音乐播放器
      </h1>

      <div class="flex flex-col lg:flex-row gap-6">

        <!-- ── Player Panel ── -->
        <div class="flex-1 flex flex-col items-center gap-5 player-card p-6 backdrop-blur-md">

          <!-- Album cover -->
          <div class="cover-wrapper" :class="{ spinning: store.isPlaying }">
            <img
              v-if="store.currentTrack?.coverUrl && !store.currentTrack.coverUrl.includes('placeholder')"
              :src="store.currentTrack.coverUrl"
              :alt="store.currentTrack.title"
              class="cover-img"
              @error="($event.target as HTMLImageElement).style.display='none'"
            />
            <div v-else class="cover-placeholder">
              <span class="text-5xl">🎵</span>
            </div>
            <div class="cover-center" />
          </div>

          <!-- Track info -->
          <div class="text-center w-full">
            <p class="text-lg font-semibold truncate" style="color:#F5DEB3;">
              {{ store.currentTrack?.title ?? '未选择歌曲' }}
            </p>
            <p class="text-sm mt-0.5" style="color:#A0785A;">
              陈奕迅 · {{ store.currentTrack?.album ?? '' }}
            </p>
          </div>

          <!-- Progress bar -->
          <div class="w-full">
            <div
              class="progress-bar cursor-pointer"
              @click="seekTo"
            >
              <div class="progress-fill" :style="{ width: progressPct + '%' }" />
              <div class="progress-thumb" :style="{ left: progressPct + '%' }" />
            </div>
            <div class="flex justify-between mt-1">
              <span class="text-xs" style="color:#666;">{{ formatTime(currentTime) }}</span>
              <span class="text-xs" style="color:#666;">{{ formatTime(duration) }}</span>
            </div>
          </div>

          <!-- Main controls -->
          <div class="flex items-center gap-5">
            <button @click="store.prev()" class="ctrl-btn" title="上一首" :disabled="!isReady">⏮</button>
            <button @click="togglePlay" class="ctrl-btn play-btn" :title="store.isPlaying ? '暂停' : '播放'">
              <span v-if="!isReady" class="loading-dot" />
              <span v-else>{{ store.isPlaying ? '⏸' : '▶' }}</span>
            </button>
            <button @click="store.next()" class="ctrl-btn" title="下一首" :disabled="!isReady">⏭</button>
          </div>

          <!-- Secondary controls -->
          <div class="flex items-center gap-3">
            <button
              @click="store.toggleShuffle()"
              class="ctrl-sm"
              :class="{ active: store.shuffleMode }"
            >🔀 {{ store.shuffleMode ? '随机' : '顺序' }}</button>
            <button @click="cycleRepeat" class="ctrl-sm">
              {{ repeatIcon }} {{ repeatLabel }}
            </button>
          </div>

          <!-- Volume -->
          <div class="flex items-center gap-3 w-full max-w-xs">
            <span style="color:#A0785A; font-size:14px;">🔈</span>
            <input
              type="range" min="0" max="1" step="0.01"
              :value="store.volume"
              @input="store.setVolume(+($event.target as HTMLInputElement).value)"
              class="volume-slider flex-1"
            />
            <span style="color:#A0785A; font-size:14px;">🔊</span>
          </div>
        </div>

        <!-- ── Playlist ── -->
        <div class="lg:w-72 player-card p-4 backdrop-blur-md overflow-y-auto" style="max-height:520px;">
          <h2 class="text-sm font-semibold mb-3 pb-2 border-b border-amber-900/40" style="color:#D4A96A;">
            播放列表 · {{ store.tracks.length }} 首
          </h2>
          <ul class="space-y-0.5">
            <li
              v-for="(track, idx) in store.tracks"
              :key="track.id"
              @click="store.jumpTo(idx); store.play(); audioRef?.play().catch(()=>{})"
              class="playlist-item px-3 py-2.5 cursor-pointer rounded-lg flex items-center gap-3"
              :class="{ 'playlist-active': idx === store.currentIndex }"
            >
              <span class="text-xs w-5 text-center flex-shrink-0" style="color:#666;">
                <span v-if="idx === store.currentIndex && store.isPlaying">▶</span>
                <span v-else>{{ idx + 1 }}</span>
              </span>
              <div class="flex-1 min-w-0">
                <p class="text-sm truncate" :style="idx === store.currentIndex ? 'color:#D4A96A;' : 'color:#F5DEB3;'">
                  {{ track.title }}
                </p>
                <p class="text-xs truncate" style="color:#6B4A2A;">{{ track.album }}</p>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <!-- Audio element -->
    <audio
      ref="audioRef"
      @ended="handleEnded"
      @error="handleError"
      @timeupdate="handleTimeUpdate"
      @loadedmetadata="handleLoadedMetadata"
      @canplay="handleCanPlay"
      preload="metadata"
    />
  </div>
  </ErrorBoundary>
</template>

<style scoped>
.music-page { font-family: 'Inter', system-ui, sans-serif; }

.player-card {
  background: rgba(42, 18, 0, 0.75);
  border: 1px solid rgba(139, 94, 60, 0.4);
  border-radius: 16px;
}

/* Cover art */
.cover-wrapper {
  width: 200px; height: 200px;
  border-radius: 50%;
  position: relative;
  flex-shrink: 0;
}
.cover-wrapper.spinning { animation: spin 8s linear infinite; }
.cover-img {
  width: 100%; height: 100%;
  border-radius: 50%;
  object-fit: cover;
  border: 4px solid rgba(139,94,60,0.6);
}
.cover-placeholder {
  width: 100%; height: 100%;
  border-radius: 50%;
  background: radial-gradient(circle, #3D1F00 30%, #1A0A00 100%);
  border: 4px solid rgba(139,94,60,0.6);
  display: flex; align-items: center; justify-content: center;
}
.cover-center {
  position: absolute; top: 50%; left: 50%;
  transform: translate(-50%, -50%);
  width: 28px; height: 28px;
  border-radius: 50%;
  background: #D4A96A;
  border: 3px solid #1A0A00;
  z-index: 1;
}
@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }

/* Progress bar */
.progress-bar {
  width: 100%; height: 4px;
  background: rgba(139,94,60,0.3);
  border-radius: 2px;
  position: relative;
  margin-top: 4px;
}
.progress-fill {
  height: 100%;
  background: linear-gradient(90deg, #D4A96A, #FF8C38);
  border-radius: 2px;
  transition: width 0.3s linear;
}
.progress-thumb {
  position: absolute; top: 50%;
  transform: translate(-50%, -50%);
  width: 12px; height: 12px;
  border-radius: 50%;
  background: #D4A96A;
  transition: left 0.3s linear;
}

/* Controls */
.ctrl-btn {
  background: rgba(61,31,0,0.8);
  border: 1px solid rgba(139,94,60,0.6);
  color: #F5DEB3;
  width: 44px; height: 44px;
  border-radius: 50%;
  font-size: 18px;
  cursor: pointer;
  display: flex; align-items: center; justify-content: center;
  transition: all 0.15s;
}
.ctrl-btn:hover:not(:disabled) { background: rgba(90,48,16,0.9); }
.ctrl-btn:disabled { opacity: 0.4; cursor: not-allowed; }
.play-btn { width: 60px; height: 60px; font-size: 22px; background: rgba(139,94,60,0.8); }
.play-btn:hover:not(:disabled) { background: #D4A96A; color: #1A0A00; }

.loading-dot {
  display: inline-block; width: 8px; height: 8px;
  border-radius: 50%; background: #D4A96A;
  animation: pulse 1s ease-in-out infinite;
}
@keyframes pulse { 0%,100% { opacity: 1; } 50% { opacity: 0.3; } }

.ctrl-sm {
  background: transparent;
  border: 1px solid rgba(90,48,16,0.6);
  color: #A0785A;
  padding: 5px 12px;
  border-radius: 8px;
  font-size: 12px;
  cursor: pointer;
  transition: all 0.15s;
}
.ctrl-sm:hover, .ctrl-sm.active { border-color: #D4A96A; color: #D4A96A; }

.volume-slider {
  -webkit-appearance: none;
  height: 4px;
  background: rgba(90,48,16,0.5);
  border-radius: 2px;
  outline: none;
}
.volume-slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  width: 14px; height: 14px;
  border-radius: 50%;
  background: #D4A96A;
  cursor: pointer;
}

/* Playlist */
.playlist-item { transition: background 0.1s; }
.playlist-item:hover { background: rgba(61,31,0,0.6); }
.playlist-active { background: rgba(90,48,16,0.7) !important; }
</style>
